-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Aanestys CASCADE;
DROP TABLE IF EXISTS Ehdokas CASCADE;
DROP TABLE IF EXISTS Aanestaneet CASCADE;
